---
- name: Update /etc/hosts with freeipa's details
  become: yes
  lineinfile:
      dest: "/etc/hosts"
      line: "{{ hostvars[freeipa_node].ansible_eth2.ipv4.address }} {{ freeipa_node }}.redhat.local {{ freeipa_node }}"
      state: present

- name: Install python novajoin
  become: yes
  package:
      name:  python-novajoin
      state: present

- name: prepare novajoin to work
  become: yes
  shell:  /usr/libexec/novajoin-ipa-setup --principal admin --password {{ freeipa_admin_password }} --server {{ freeipa_node }}.redhat.local --realm REDHAT.LOCAL --domain redhat.local --hostname {{ groups['undercloud'][0] }}.redhat.local --precreate
  register: novajoin

- name: edit undercloud.conf
  blockinfile:
      path: ~/undercloud.conf
      backup: yes
      marker: "# {mark} TLS EVERYWHERE SETTINGS -->"
      content: |
          enable_novajoin = True
          ipa_otp = {{ novajoin.stdout }}
          undercloud_hostname = {{ groups['undercloud'][0] }}.redhat.local
          undercloud_nameservers = {{ hostvars[freeipa_node].ansible_eth2.ipv4.address }}
          overcloud_domain_name = redhat.local
