---
- name: install virtualenv requirments for pip
  become: yes
  package:
      name:
        - gcc
        - python-devel
        - python-setuptools
        - libffi-devel
      state: present

- name: install pip
  become: yes
  easy_install:
      name: pip

- name: install virtualenv pip module
  become: yes
  pip:
      name: virtualenv
      version: 15.0.3

# required to avoid any conflicts in venv with
# different packages versions (especially shade)
- name: cleanup shade venv if present
  file:
      state: absent
      path: "{{ shade_path_venv }}"

# installing setuptools and pip must happen before other packages and separated
# do not use shimming for these two special packages
- name: shade virtualenv core deps
  pip:
      name: "{{ item }}"
      virtualenv: "{{ shade_path_venv }}"
  with_items:
    - setuptools>=17.0
    - pip>=9.0.1

- name: shade virtualenv deps
  pip:
      name:
        - pytz>=2016.4
        - shade>=1.26.0
        - keystoneauth1>=3.3.0
      # use ranges, if needed, but always mention bug when you do
      virtualenv: "{{ shade_path_venv }}"
